# argocd-myapp.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
  namespace: openshift-gitops          # this is where Argo CD runs
spec:
  project: default
  source:
    repoURL: https://github.com/islamr12/argocd-openshift
    targetRevision: main
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: bubble-animation
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true